HEADER_MANUFACTURER = "Manufacturer"
HEADER_QUANTITY = "Quantity"
HEADER_VALUE = "Value"
HEADER_URL = "URL"
HEADER_PRODUCT_NUM = "Product Number"
HEADER_STANDARD_PRICING = "Standard Pricing"
HEADER_FOOTPRINT = "Footprint"
HEADER_TOLERANCE = "Tolerance"
HEADER_POWER = "Power (Watts)"
HEADER_VR = "Voltage Rating"
HEADER_DATASHEET_URL = "Datasheet URL"

HEADER_LISTING = [
    HEADER_MANUFACTURER,
    HEADER_QUANTITY,
    HEADER_VALUE,
    HEADER_FOOTPRINT,
    HEADER_URL,
    HEADER_PRODUCT_NUM,
    HEADER_STANDARD_PRICING,
    HEADER_TOLERANCE,
    HEADER_POWER,
    HEADER_VR,
    HEADER_DATASHEET_URL
]