HEADER_MANUFACTURER = "Manufacturer"
HEADER_QUANTITY = "Quantity"
HEADER_VALUE = "Value"
HEADER_URL = "URL"
HEADER_PRODUCT_NUM = "Product Number"
HEADER_STANDARD_PRICING = "Standard Pricing"
HEADER_FOOTPRINT = "Footprint"

HEADER_LISTING = [
    HEADER_MANUFACTURER,
    HEADER_QUANTITY,
    HEADER_VALUE,
    HEADER_URL,
    HEADER_PRODUCT_NUM,
    HEADER_STANDARD_PRICING
]